services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-app
    restart: unless-stopped
    ports:
      - "8080:80"    # افتح http://localhost:8080
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: task-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
